# Configuraci칩n de Build (opcional si ya est치 en la UI de Netlify, pero bueno tenerla)
[build]
  command = "npm run build" # Tu comando de build de client/package.json
  publish = "dist"          # Tu directorio de publicaci칩n relativo a 'client'

# Regla de redirecci칩n para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
